// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options  .dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlHAUGx79rKcS6xnUKPF0cKngh4hYGI0E',
    appId: '1:959730194266:web:17ef78c7e9d6aec6e70563',
    messagingSenderId: '959730194266',
    projectId: 'expenses-tracker-3231f',
    authDomain: 'expenses-tracker-3231f.firebaseapp.com',
    storageBucket: 'expenses-tracker-3231f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGmTlFJ7I8aoSxgkLg_U62-1B4vFbNqGA',
    appId: '1:959730194266:android:bfebb21f9fd6e053e70563',
    messagingSenderId: '959730194266',
    projectId: 'expenses-tracker-3231f',
    storageBucket: 'expenses-tracker-3231f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4RQGwRzEiNJY5gfm1ZI0lIyN5sEYsDds',
    appId: '1:959730194266:ios:396c1c1f9a7881eee70563',
    messagingSenderId: '959730194266',
    projectId: 'expenses-tracker-3231f',
    storageBucket: 'expenses-tracker-3231f.firebasestorage.app',
    iosBundleId: 'com.example.expensesTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4RQGwRzEiNJY5gfm1ZI0lIyN5sEYsDds',
    appId: '1:959730194266:ios:396c1c1f9a7881eee70563',
    messagingSenderId: '959730194266',
    projectId: 'expenses-tracker-3231f',
    storageBucket: 'expenses-tracker-3231f.firebasestorage.app',
    iosBundleId: 'com.example.expensesTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlHAUGx79rKcS6xnUKPF0cKngh4hYGI0E',
    appId: '1:959730194266:web:fadedfc3114924f3e70563',
    messagingSenderId: '959730194266',
    projectId: 'expenses-tracker-3231f',
    authDomain: 'expenses-tracker-3231f.firebaseapp.com',
    storageBucket: 'expenses-tracker-3231f.firebasestorage.app',
  );

}