// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXOnK1CWoQac6mTnAy39bGfAUVK9phiq8',
    appId: '1:70573966202:web:45d959dbde529aa87a0cc3',
    messagingSenderId: '70573966202',
    projectId: 'expenses-tracker-1926d',
    authDomain: 'expenses-tracker-1926d.firebaseapp.com',
    storageBucket: 'expenses-tracker-1926d.firebasestorage.app',
    measurementId: 'G-XFC5VZ10BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0FvktU-D6E42LOgTNTfEjoZsglaA6ukg',
    appId: '1:70573966202:android:06759aef579f76547a0cc3',
    messagingSenderId: '70573966202',
    projectId: 'expenses-tracker-1926d',
    storageBucket: 'expenses-tracker-1926d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOb0ClkObmaMDTfKjuEdp_8grjjkijTFk',
    appId: '1:70573966202:ios:223606696958eb107a0cc3',
    messagingSenderId: '70573966202',
    projectId: 'expenses-tracker-1926d',
    storageBucket: 'expenses-tracker-1926d.firebasestorage.app',
    iosBundleId: 'com.example.expensesTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOb0ClkObmaMDTfKjuEdp_8grjjkijTFk',
    appId: '1:70573966202:ios:223606696958eb107a0cc3',
    messagingSenderId: '70573966202',
    projectId: 'expenses-tracker-1926d',
    storageBucket: 'expenses-tracker-1926d.firebasestorage.app',
    iosBundleId: 'com.example.expensesTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXOnK1CWoQac6mTnAy39bGfAUVK9phiq8',
    appId: '1:70573966202:web:cf3f368a6c49bd6f7a0cc3',
    messagingSenderId: '70573966202',
    projectId: 'expenses-tracker-1926d',
    authDomain: 'expenses-tracker-1926d.firebaseapp.com',
    storageBucket: 'expenses-tracker-1926d.firebasestorage.app',
    measurementId: 'G-T7G0FSCV0V',
  );
}
